spring:
  application:
    name: auth-server

server:
  address: 127.0.0.1
  port: 8088
  tomcat:
    threads:
      max: 12
      min-spare: 6

logging:
  level:
    ROOT: warn
    me.card.switchv1: warn